name: librevault
version: 0.1.0
summary: Librevault file sharing platform
description: |
  Librevault file sharing platform
confinement: devmode
base: core18
parts:
  librevault:
    source: .
    plugin: cmake
    configflags:
      - -DCMAKE_BUILD_TYPE=Release
    build-packages:
      - build-essential
      - python3.7-dev
      - python3.7-venv
      - python3-pip
      - python3-setuptools
      - python3-wheel
      - bash
    override-build: |
      python3.7 -m pip install poetry setuptools wheel
      python3.7 -m venv .venv
      cp $SNAPCRAFT_PART_SRC/pyproject.toml .
      poetry install
      .venv/bin/conan remote add -f bincrafters https://api.bintray.com/conan/bincrafters/public-conan
      .venv/bin/conan profile new --detect --force default
      .venv/bin/conan profile update settings.compiler.libcxx=libstdc++11 default
      .venv/bin/conan install $SNAPCRAFT_PART_SRC --build=missing --build=cascade
      snapcraftctl build
